apiVersion: v1
kind: ConfigMap
metadata:
  name: tamilnadu-app-config
  namespace: production
data:
  NODE_ENV: "production"
  AWS_REGION: "eu-north-1"
  AWS_S3_BUCKET_NAME: "tamilnadu-voting-app-bucket"
  APP_PORT: "4000"
  LOG_LEVEL: "info"
