apiVersion: v1
kind: Secret
metadata:
  name: tamilnadu-app-secrets
  namespace: production
type: Opaque
data:
  # Base64 encoded values
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9wb25uaTE3MTkzX2RiX3VzZXI6cUN2dzZHExNzJhclZjOVBRe0B0YW1pbG5hZG4ua3psZGRjay5tb25nb2RiLm5ldC8/YXBwTmFtZQ==
  AWS_ACCESS_KEY_ID: QUtJQVJBQVY...
  AWS_SECRET_ACCESS_KEY: K0hBWCtWRTA...
